import { ISerializer } from "./ISerializer";
import { GetDate } from "./tools";
import { ArrayType, ClassType, LinkType, SimpleType } from "./types";

export class CppSerializer extends ISerializer {
    protected begin() {
        this.source = `/**\n * @file ${this.namespaceName}.cpp\n`;
        this.source += ` * @author ${this.author}\n * @brief Autogenerated by MckAudio TypeGenerator\n`;
        this.source += ` * @date ${GetDate()}\n */\n\n`;
        this.source += `#include "${this.namespaceName}.hpp"\n\n`;
        this.source += `namespace ${this.namespaceName} {\n`;
    }

    protected end() {
        this.source += `} // namespace ${this.namespaceName}\n`;
    }

    addClassMember(member: ClassType) {

    }

    addSimpleMember(member: SimpleType) {

    }

    addLinkMember(member: LinkType) {

    }

    addArrayMember(member: ArrayType) {

    }

}